http_directory          = ""
vm_name                 = ""
vm_guest_os_type        = ""
vm_version              = 
vm_firmware             = ""
vm_cdrom_type           = ""
vm_cpu_sockets          = 
vm_cpu_cores            = 
vm_mem_size             = 
vm_disk_size            = 
thin_provision          = 
disk_eagerly_scrub      = 
vm_disk_controller_type = [""]
vm_network_card         = ""
vm_boot_wait            = ""
ssh_host                = ""
ssh_username            = ""
ssh_password            = ""
iso_file                = ""
iso_checksum            = ""
iso_checksum_type       = ""
iso_url                 = ""
shell_scripts           = ["./scripts/setup_ubuntu2204.sh"]